import type { Booking, DateBlock } from "./calander.types";

export const BOOKINGS: Booking[] = [
  {
    id: "b1",
    unitId: "u1",
    guest: "Grace Adeyemi",
    start: 12,
    end: 15,
    status: "CONFIRMED",
    phone: "08012345678",
    email: "grace@example.com",
    guests: 4,
    total: 36000000,
    notes: null,
    createdBy: "Adaeze Nwosu",
  },
  {
    id: "b2",
    unitId: "u1",
    guest: "Emeka Obi",
    start: 15,
    end: 18,
    status: "CONFIRMED",
    phone: "08033391220",
    email: "emeka@example.com",
    guests: 2,
    total: 36000000,
    notes: "Same-day changeover after Grace. Cleaners booked for 11am.",
    createdBy: "Adaeze Nwosu",
  },
  {
    id: "b3",
    unitId: "u2",
    guest: "Halima Sule",
    start: 3,
    end: 9,
    status: "CHECKED_OUT",
    phone: "08099120044",
    email: "halima@example.com",
    guests: 3,
    total: 39000000,
    notes: null,
    createdBy: "Adaeze Nwosu",
  },
  {
    id: "b4",
    unitId: "u3",
    guest: "Kunle Ade",
    start: 1,
    end: 5,
    status: "CHECKED_OUT",
    phone: "08144220091",
    email: "kunle@example.com",
    guests: 2,
    total: 12800000,
    notes: null,
    createdBy: "Chidi Bassey",
  },
  {
    id: "b5",
    unitId: "u3",
    guest: "Zainab Yusuf",
    start: 22,
    end: 28,
    status: "CONFIRMED",
    phone: "08066554433",
    email: "zainab@example.com",
    guests: 2,
    total: 19200000,
    notes: null,
    createdBy: "Chidi Bassey",
  },
  {
    id: "b6",
    unitId: "u4",
    guest: "Peter Nnamdi",
    start: 10,
    end: 13,
    status: "CHECKED_IN",
    phone: "08023110987",
    email: "peter@example.com",
    guests: 7,
    total: 55500000,
    notes: "Arriving late, key with security.",
    createdBy: "Adaeze Nwosu",
  },
  {
    id: "b7",
    unitId: "u6",
    guest: "Ada Uche",
    start: 16,
    end: 21,
    status: "CONFIRMED",
    phone: "08155667788",
    email: "ada@example.com",
    guests: 5,
    total: 45000000,
    notes: null,
    createdBy: "Chidi Bassey",
  },
  {
    id: "b8",
    unitId: "u7",
    guest: "Ngozi Iwu",
    start: 2,
    end: 7,
    status: "CHECKED_OUT",
    phone: "08077231190",
    email: "ngozi@example.com",
    guests: 3,
    total: 26000000,
    notes: null,
    createdBy: "Biodun Properties",
  },
  {
    id: "b9",
    unitId: "u7",
    guest: "Sadiq Bello",
    start: 19,
    end: 24,
    status: "CONFIRMED",
    phone: "08033448821",
    email: "sadiq@example.com",
    guests: 2,
    total: 26000000,
    notes: null,
    createdBy: "Biodun Properties",
  },
];

export const BLOCKS: DateBlock[] = [
  { id: "k1", unitId: "u2", reason: "Kitchen renovation", start: 20, end: 24 },
  { id: "k2", unitId: "u6", reason: "Owner's use", start: 6, end: 8 },
];
