import type { AccessLogEntry, DocumentRecord } from "./document.type";

export const DOCUMENTS: DocumentRecord[] = [
  {
    id: "d1",
    documentName: "Title Deed",
    documentCategory: "TITLE",
    unitId: "u1",
    date: "14 Jul 2026",
    uploadedBy: "Tunde Balogun",
    mimeLabel: "PDF",
    sizeLabel: "6.1 MB",
  },
  {
    id: "d2",
    documentName: "Tenancy Agreement 2026",
    documentCategory: "LEASE",
    unitId: "u1",
    date: "2 Jul 2026",
    uploadedBy: "Adaeze Nwosu",
    mimeLabel: "PDF",
    sizeLabel: "820 KB",
  },
  {
    id: "d3",
    documentName: "July inspection report",
    documentCategory: "INSPECTION",
    unitId: "u2",
    date: "28 Jul 2026",
    uploadedBy: "Manny Okonkwo",
    mimeLabel: "PDF",
    sizeLabel: "1.4 MB",
  },
  {
    id: "d4",
    documentName: "AC servicing invoice",
    documentCategory: "MAINTENANCE",
    unitId: "u2",
    date: "21 Jul 2026",
    uploadedBy: "Manny Okonkwo",
    mimeLabel: "JPEG",
    sizeLabel: "2.2 MB",
  },
  {
    id: "d5",
    documentName: "Owner ID — NIN slip",
    documentCategory: "ID_KYC",
    unitId: "u2",
    date: "9 Jun 2026",
    uploadedBy: "Tunde Balogun",
    mimeLabel: "PNG",
    sizeLabel: "740 KB",
  },
  {
    id: "d6",
    documentName: "Proof of ownership",
    documentCategory: "PROOF_OF_OWNERSHIP",
    unitId: "u4",
    date: "3 Jun 2026",
    uploadedBy: "Adaeze Nwosu",
    mimeLabel: "PDF",
    sizeLabel: "3.0 MB",
  },
  {
    id: "d7",
    documentName: "Plumbing repair note",
    documentCategory: "MAINTENANCE",
    unitId: "u1",
    date: "19 Jul 2026",
    uploadedBy: "Manny Okonkwo",
    mimeLabel: "DOCX",
    sizeLabel: "96 KB",
  },
];

export const ACCESS_LOG: AccessLogEntry[] = [
  {
    user: "Tunde Balogun",
    actionText: "downloaded this document",
    meta: "105.112.44.9 · owner",
    when: "26 Jul, 9:40am",
    tone: "tan",
  },
  {
    user: "Adaeze Nwosu",
    actionText: "viewed this document",
    meta: "102.89.3.14 · company admin",
    when: "20 Jul, 2:05pm",
    tone: "ink",
  },
  {
    user: "Adaeze Nwosu",
    actionText: "uploaded this document",
    meta: "102.89.3.14 · company admin",
    when: "14 Jul, 10:11am",
    tone: "green",
  },
];
