import type { MaintenanceRecord, Unit } from "./units.types";

export const UNITS: Unit[] = [
  {
    id: "u1",
    photo: "1600607687939-ce8a6c25118c",
    unitName: "Penthouse 5C",
    unitType: "PENTHOUSE",
    bedrooms: 3,
    bathrooms: 3,
    toilets: 4,
    parlors: 2,
    maxGuests: 6,
    pricePerNight: 12000000,
    amenities: [
      "WIFI",
      "SWIMMING_POOL",
      "GYM",
      "ELEVATOR",
      "SECURITY",
      "AIR_CONDITIONING",
    ],
    propertyId: "p1",
    propertyName: "Lekki Court",
    propertyCity: "Lagos",
    archivedAt: null,
    description:
      "Top-floor penthouse with pool access, a separate guest parlour and a dedicated lift lobby.",
    owners: [{ fullName: "Tunde Balogun", email: "tunde@example.com" }],
  },
  {
    id: "u2",
    photo: "1522708323590-d24dbb6b0267",
    unitName: "Flat 14",
    unitType: "FLAT",
    bedrooms: 2,
    bathrooms: 2,
    toilets: 3,
    parlors: 1,
    maxGuests: 4,
    pricePerNight: 6500000,
    ownerRatePerNight: 5000000,
    amenities: ["WIFI", "GENERATOR", "PARKING", "SECURITY"],
    propertyId: "p1",
    propertyName: "Lekki Court",
    propertyCity: "Lagos",
    archivedAt: null,
    description:
      "Two-bedroom flat on the third floor, generator-backed, parking for one car.",
    owners: [{ fullName: "Tunde Balogun", email: "tunde@example.com" }],
  },
  {
    id: "u3",
    photo: "1554995207-c18c203602cb",
    unitName: "Studio 2B",
    unitType: "STUDIO",
    bedrooms: 1,
    bathrooms: 1,
    toilets: 1,
    parlors: 0,
    maxGuests: 2,
    pricePerNight: 3200000,
    amenities: ["WIFI", "AIR_CONDITIONING", "KITCHEN"],
    propertyId: "p4",
    propertyName: "Yaba Studios",
    propertyCity: "Lagos",
    archivedAt: null,
    description: "Compact studio five minutes from the tech cluster.",
    owners: [{ fullName: "Ifeoma Eze", email: "ifeoma@example.com" }],
  },
  {
    id: "u4",
    photo: "1600585154340-be6161a56a0c",
    unitName: "Duplex A",
    unitType: "DUPLEX",
    bedrooms: 4,
    bathrooms: 4,
    toilets: 5,
    parlors: 2,
    maxGuests: 8,
    pricePerNight: 18500000,
    amenities: [
      "WIFI",
      "GENERATOR",
      "PARKING",
      "SECURITY",
      "WASHING_MACHINE",
      "BALCONY",
    ],
    propertyId: "p3",
    propertyName: "Maitama Terraces",
    propertyCity: "Abuja",
    archivedAt: null,
    description:
      "Four-bedroom duplex with staff quarters and a walled compound.",
    owners: [{ fullName: "Ifeoma Eze", email: "ifeoma@example.com" }],
  },
  {
    id: "u6",
    photo: "1600566753086-00f18fb6b3ea",
    unitName: "Terrace 3",
    unitType: "FLAT",
    bedrooms: 3,
    bathrooms: 3,
    toilets: 4,
    parlors: 1,
    maxGuests: 6,
    pricePerNight: 9000000,
    amenities: ["WIFI", "INVERTER", "PARKING", "TV"],
    propertyId: "p3",
    propertyName: "Maitama Terraces",
    propertyCity: "Abuja",
    archivedAt: null,
    description: "Mid-terrace unit, inverter-backed, quiet street.",
    owners: [{ fullName: "Tunde Balogun", email: "tunde@example.com" }],
  },
  {
    id: "u5",
    photo: "1493809842364-78817add7ffb",
    unitName: "Self Contain 7",
    unitType: "SELF_CONTAIN",
    bedrooms: 1,
    bathrooms: 1,
    toilets: 1,
    parlors: 0,
    maxGuests: 2,
    pricePerNight: 2800000,
    amenities: ["WIFI", "SECURITY"],
    propertyId: "p4",
    propertyName: "Yaba Studios",
    propertyCity: "Lagos",
    archivedAt: "2026-06-11",
    description: "Off the market pending repairs.",
    owners: [],
  },
  {
    id: "u7",
    photo: "1502672023488-70e25813eb80",
    unitName: "Flat 88",
    unitType: "FLAT",
    bedrooms: 2,
    bathrooms: 2,
    toilets: 2,
    parlors: 1,
    maxGuests: 4,
    pricePerNight: 5200000,
    ownerRatePerNight: 4200000,
    amenities: ["WIFI", "GENERATOR", "PARKING"],
    propertyId: "x1",
    propertyName: "Biodun Court",
    propertyCity: "Abuja",
    archivedAt: null,
    managedBy: "Biodun Properties",
    description: "Two-bedroom flat managed by Biodun Properties.",
    owners: [{ fullName: "Tunde Balogun", email: "tunde@example.com" }],
  },
];

export const MAINTENANCE: MaintenanceRecord[] = [
  {
    id: "x1",
    unitId: "u1",
    title: "Generator service",
    type: "SCHEDULED",
    category: "REPAIR",
    status: "COMPLETED",
    cost: 4500000,
    performedAt: "12 Jul 2026",
  },
  {
    id: "x2",
    unitId: "u1",
    title: "Leaking kitchen tap",
    type: "REACTIVE",
    category: "REPAIR",
    status: "IN_PROGRESS",
    cost: 1800000,
    performedAt: "30 Jul 2026",
  },
  {
    id: "x3",
    unitId: "u2",
    title: "Repaint guest bedroom",
    type: "SCHEDULED",
    category: "OTHER",
    status: "PENDING",
    cost: 2400000,
    performedAt: "10 Aug 2026",
  },
  {
    id: "x4",
    unitId: "u2",
    title: "Deep clean, changeover",
    type: "SCHEDULED",
    category: "CLEANING",
    status: "COMPLETED",
    cost: 1200000,
    performedAt: "22 Jul 2026",
  },
];

/** Photos behind the unit gallery. */
export const GALLERY_PHOTOS = [
  "1502672260266-1c1ef2d93688",
  "1484154218962-a197022b5858",
  "1522771739844-6a9f6d5f14af",
  "1584622650111-993a426fbf0a",
  "1556909212-d5b604d0c90d",
  "1560448204-e02f11c3d0e2",
];

export const DAMAGE_PHOTOS = [
  { photo: "1620626011761-996317b8d101", name: "IMG_8841" },
  { photo: "1584622650111-993a426fbf0a", name: "IMG_8842" },
];
